/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.BudgetsDetails;
import model.dao.BudgetsDetailsDAO;

/**
 *
 * @author Tong
 */
public class FBudgetsDetails extends javax.swing.JFrame {

    /**
     * Creates new form FBudgetsDetails
     */
    public FBudgetsDetails() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTBudgetDetails = new javax.swing.JTable();
        txtIdBudgetDetails = new javax.swing.JTextField();
        txtIdProdutosBudgetDetails = new javax.swing.JTextField();
        txtSubtotalBudgetDetails = new javax.swing.JTextField();
        txtQtBudgetDetails = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtPrecoBudgetDetails = new javax.swing.JTextField();
        txtIdBudgetBudgetDetails = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        txtBuscaBudgetDetails = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTBudgetDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "PREÇO", "QUANTIDADE", "SUBTOTAL", "ID PRODUTOS", "ID BUDGET"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBudgetDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTBudgetDetailsMouseClicked(evt);
            }
        });
        jTBudgetDetails.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTBudgetDetailsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTBudgetDetails);

        jLabel6.setText("QUANTIDADE");

        jLabel2.setText("PREÇO");

        jLabel4.setText("SUBTOTAL");

        jLabel11.setText("ID PRODUTOS");

        jLabel9.setText("ID");

        jLabel12.setText("ID BUDGET");

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtBuscaBudgetDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaBudgetDetailsActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(txtPrecoBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtQtBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addGap(163, 163, 163)
                                .addComponent(txtBuscaBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtSubtotalBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtIdProdutosBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtIdBudgetBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 846, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQtBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(txtPrecoBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel9))
                        .addGap(10, 10, 10)
                        .addComponent(txtIdBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSubtotalBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProdutosBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdBudgetBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscaBudgetDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton2)))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTBudgetDetails.getModel();
        modelo.setNumRows(0);
        BudgetsDetailsDAO pdao = new BudgetsDetailsDAO();

        for (BudgetsDetails p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getPrice(),
                p.getAmount(),
                p.getSubtotal(),
                p.getBudgetsId(),
                p.getProductsId()
            });

        }

    }
    
    
    public void readJTableForDesc(String desc) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTBudgetDetails.getModel();
        modelo.setNumRows(0);
        BudgetsDetailsDAO pdao = new BudgetsDetailsDAO();

        for (BudgetsDetails p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getPrice(),
                p.getAmount(),
                p.getSubtotal(),
                p.getBudgetsId(),
                p.getProductsId()
            });

        }

    }
    
    private void jTBudgetDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBudgetDetailsMouseClicked
        if (jTBudgetDetails.getSelectedRow() != -1) {

            txtIdBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 1).toString());
            txtPrecoBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 2).toString());
            txtQtBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 3).toString());
            txtSubtotalBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 4).toString());
            txtIdBudgetBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 5).toString());
            txtIdProdutosBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 6).toString());
        
        }
    }//GEN-LAST:event_jTBudgetDetailsMouseClicked

    private void jTBudgetDetailsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTBudgetDetailsKeyReleased
        if (jTBudgetDetails.getSelectedRow() != -1) {

            txtIdBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 1).toString());
            txtPrecoBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 2).toString());
            txtQtBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 3).toString());
            txtSubtotalBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 4).toString());
            txtIdBudgetBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 5).toString());
            txtIdProdutosBudgetDetails.setText(jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 6).toString());
        }
    }//GEN-LAST:event_jTBudgetDetailsKeyReleased

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            readJTableForDesc(txtBuscaBudgetDetails.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FBudgetsDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtBuscaBudgetDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaBudgetDetailsActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaBudgetDetailsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTBudgetDetails.getSelectedRow() != -1) {

            try {

                BudgetsDetails p = new BudgetsDetails();
                BudgetsDetailsDAO dao = new BudgetsDetailsDAO();

                p.setId(Integer.parseInt(txtIdBudgetDetails.getText()));
                p.setPrice(Integer.parseInt(txtPrecoBudgetDetails.getText()));
                p.setAmount(Integer.parseInt(txtQtBudgetDetails.getText()));
                p.setSubtotal(Double.parseDouble(txtSubtotalBudgetDetails.getText()));
                p.setBudgetsId(Integer.parseInt(txtIdBudgetBudgetDetails.getText()));
                p.setProductsId(Integer.parseInt(txtIdProdutosBudgetDetails.getText()));
                p.setId((int) jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 0));

                
                dao.alter(p);
              

                txtIdBudgetDetails.setText("");
                txtPrecoBudgetDetails.setText("");
                txtQtBudgetDetails.setText("");
                txtSubtotalBudgetDetails.setText("");
                txtIdProdutosBudgetDetails.setText("");
                txtIdBudgetBudgetDetails.setText("");
                
                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FBudgetsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTBudgetDetails.getSelectedRow() != -1) {

            try {

                BudgetsDetails p = new BudgetsDetails();
                BudgetsDetailsDAO dao = new BudgetsDetailsDAO();

                p.setId((int) jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 0));

                dao.delete(p);

                txtIdBudgetDetails.setText("");
                txtPrecoBudgetDetails.setText("");
                txtQtBudgetDetails.setText("");
                txtSubtotalBudgetDetails.setText("");
                txtIdProdutosBudgetDetails.setText("");
                txtIdBudgetBudgetDetails.setText("");

                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex) {
                Logger.getLogger(FBudgetsDetails.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um budget para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            BudgetsDetails p = new BudgetsDetails();
            BudgetsDetailsDAO dao = new BudgetsDetailsDAO();

                p.setId(Integer.parseInt(txtIdBudgetDetails.getText()));
                p.setPrice(Integer.parseInt(txtPrecoBudgetDetails.getText()));
                p.setAmount(Integer.parseInt(txtQtBudgetDetails.getText()));
                p.setSubtotal(Double.parseDouble(txtSubtotalBudgetDetails.getText()));
                p.setBudgetsId(Integer.parseInt(txtIdBudgetBudgetDetails.getText()));
                p.setProductsId(Integer.parseInt(txtIdProdutosBudgetDetails.getText()));
                p.setId((int) jTBudgetDetails.getValueAt(jTBudgetDetails.getSelectedRow(), 0));
                dao.create(p);

                txtIdBudgetDetails.setText("");
                txtPrecoBudgetDetails.setText("");
                txtQtBudgetDetails.setText("");
                txtSubtotalBudgetDetails.setText("");
                txtIdProdutosBudgetDetails.setText("");
                txtIdBudgetBudgetDetails.setText("");

            readJTable();

        } catch (SQLException ex) {
            Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(FBudget.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FBudgetsDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FBudgetsDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTBudgetDetails;
    private javax.swing.JTextField txtBuscaBudgetDetails;
    private javax.swing.JTextField txtIdBudgetBudgetDetails;
    private javax.swing.JTextField txtIdBudgetDetails;
    private javax.swing.JTextField txtIdProdutosBudgetDetails;
    private javax.swing.JTextField txtPrecoBudgetDetails;
    private javax.swing.JTextField txtQtBudgetDetails;
    private javax.swing.JTextField txtSubtotalBudgetDetails;
    // End of variables declaration//GEN-END:variables
}
