/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.dao.ClientsDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Clients;
/**
 *
 * @author Tong
 */
public class FClients extends javax.swing.JFrame {

    /**
     * Creates new form Clients
     */
    public FClients() {
        initComponents();
        jButton4.setEnabled(false);
        /*DefaultTableModel modelo = (DefaultTableModel)jTClients.getModel();
       jTClients.setRowSorter(new TableRowSorter(modelo));

        readJTable();*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCepClients = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNomeClients = new javax.swing.JTextField();
        txtCpfClients = new javax.swing.JTextField();
        txtEstadoClients = new javax.swing.JTextField();
        txtCidadeClients = new javax.swing.JTextField();
        txtComplementoClients = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEnderecoClients = new javax.swing.JTextField();
        txtEmailClients = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtTelFixoClients = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTClients = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtBuscaClients = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtCelularClients = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtIdClients = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtNumEnderecoClients = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("CIDADE");

        jLabel1.setText("ENDEREÇO");

        jLabel5.setText("NOME");

        jLabel2.setText("CPF");

        jLabel6.setText("COMPLEMENTO");

        jLabel3.setText("CEP");

        jLabel7.setText("ESTADO");

        jLabel8.setText("CELULAR");

        jLabel11.setText("TELEFONE FIXO");

        jTClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "CPF", "NOME", "ENDEREÇO", "Nº ENDEREÇO", "COMPLEMENTO", "ESTADO", "CIDADE", "CEP", "CELULAR", "TELEFONE FIXO", "EMAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTClientsMouseClicked(evt);
            }
        });
        jTClients.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTClientsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTClients);

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtBuscaClients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaClientsActionPerformed(evt);
            }
        });

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel9.setText("EMAIL");

        jLabel10.setText("ID");

        jLabel12.setText("Nº DO ENDEREÇO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1029, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jButton2)
                        .addGap(26, 26, 26)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(txtTelFixoClients, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(txtCelularClients, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmailClients, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77)
                                .addComponent(txtBuscaClients, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton4)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txtEnderecoClients, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtCidadeClients, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtComplementoClients)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(73, 73, 73))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtNomeClients, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpfClients, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtIdClients, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCepClients, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoClients, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumEnderecoClients, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtNomeClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCpfClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIdClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCepClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNumEnderecoClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEnderecoClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCidadeClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtComplementoClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTelFixoClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCelularClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtEmailClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtBuscaClients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTClients.getModel();
        modelo.setNumRows(0);
        ClientsDAO pdao = new ClientsDAO();

        for (Clients p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getCpf(),
                p.getName(),
                p.getAddress(),
                p.getAddress_number(),
                p.getComplement(),
                p.getState(),
                p.getCity(),
                p.getCep(),
                p.getCell_phone(),
                p.getFixed_phone(),
                p.getEmail()
            });

        }

    }
    
    
    public void readJTableForDesc(String desc) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTClients.getModel();
        modelo.setNumRows(0);
        ClientsDAO pdao = new ClientsDAO();

        for (Clients p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getCpf(),
                p.getName(),
                p.getAddress(),
                p.getAddress_number(),
                p.getComplement(),
                p.getState(),
                p.getCity(),
                p.getCep(),
                p.getCell_phone(),
                p.getFixed_phone(),
                p.getEmail()
            });

        }
    }
    
    private void jTClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTClientsMouseClicked
        if (jTClients.getSelectedRow() != -1) {
            
            txtIdClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 1).toString());
            txtCpfClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 2).toString());
            txtNomeClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 3).toString());
            txtEnderecoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 4).toString());
            txtNumEnderecoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 5).toString());
            txtComplementoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 6).toString());
            txtEstadoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 7).toString());
            txtCidadeClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 8).toString());
            txtCepClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 9).toString());
            txtCelularClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 10).toString());
            txtTelFixoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 11).toString());
            txtEmailClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 12).toString());
        }
    }//GEN-LAST:event_jTClientsMouseClicked

    private void jTClientsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTClientsKeyReleased
        if (jTClients.getSelectedRow() != -1) {

            txtIdClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 1).toString());
            txtCpfClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 2).toString());
            txtNomeClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 3).toString());
            txtEnderecoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 4).toString());
            txtNumEnderecoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 5).toString());
            txtComplementoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 6).toString());
            txtEstadoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 7).toString());
            txtCidadeClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 8).toString());
            txtCepClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 9).toString());
            txtCelularClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 10).toString());
            txtTelFixoClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 11).toString());
            txtEmailClients.setText(jTClients.getValueAt(jTClients.getSelectedRow(), 12).toString());
        }
    }//GEN-LAST:event_jTClientsKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Clients p = new Clients();
            ClientsDAO dao = new ClientsDAO();

            p.setId(Integer.parseInt(txtIdClients.getText()));
            p.setCpf(txtCpfClients.getText());
            p.setName(txtNomeClients.getText());
            p.setAddress(txtEnderecoClients.getText());
            p.setAddress_number(txtNumEnderecoClients.getText());
            p.setComplement(txtComplementoClients.getText());
            p.setState(txtEstadoClients.getText());
            p.setCity(txtCidadeClients.getText());
            p.setCep(txtCepClients.getText());
            p.setFixed_phone(txtTelFixoClients.getText());
            p.setCell_phone(txtCelularClients.getText());
            p.setEmail(txtEmailClients.getText());
            dao.create(p);

            txtCpfClients.setText("");
            txtNomeClients.setText("");
            txtEnderecoClients.setText("");
            txtComplementoClients.setText("");
            txtEstadoClients.setText("");
            txtCidadeClients.setText("");
            txtCepClients.setText("");
            txtTelFixoClients.setText("");
            txtCelularClients.setText("");
            txtEmailClients.setText("");
            txtComplementoClients.setText("");
            txtIdClients.setText("");
            readJTable();

        } catch (SQLException ex) {
            Logger.getLogger(FClients.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTClients.getSelectedRow() != -1) {

            try {

                Clients p = new Clients();
                ClientsDAO dao = new ClientsDAO();

                p.setId((int) jTClients.getValueAt(jTClients.getSelectedRow(), 0));

                dao.delete(p);

                txtCpfClients.setText("");
                txtNomeClients.setText("");
                txtEnderecoClients.setText("");
                txtComplementoClients.setText("");
                txtEstadoClients.setText("");
                txtCidadeClients.setText("");
                txtCepClients.setText("");
                txtTelFixoClients.setText("");
                txtCelularClients.setText("");
                txtEmailClients.setText("");
                txtComplementoClients.setText("");
                txtIdClients.setText("");

                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FClients.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um cliente para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTClients.getSelectedRow() != -1) {

            try {

                Clients p = new Clients();
                ClientsDAO dao = new ClientsDAO();

                p.setId(Integer.parseInt(txtIdClients.getText()));
                p.setCpf(txtCpfClients.getText());
                p.setName(txtNomeClients.getText());
                p.setAddress(txtEnderecoClients.getText());
                p.setAddress_number(txtNumEnderecoClients.getText());
                p.setComplement(txtComplementoClients.getText());
                p.setState(txtEstadoClients.getText());
                p.setCity(txtCidadeClients.getText());
                p.setCep(txtCepClients.getText());
                p.setFixed_phone(txtTelFixoClients.getText());
                p.setCell_phone(txtCelularClients.getText());
                p.setEmail(txtEmailClients.getText());
                p.setId((int) jTClients.getValueAt(jTClients.getSelectedRow(), 0));

                try {
                    dao.alter(p);
                } catch (SQLException ex) {
                    Logger.getLogger(FClients.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(FClients.class.getName()).log(Level.SEVERE, null, ex);
                }

                txtCpfClients.setText("");
                txtNomeClients.setText("");
                txtEnderecoClients.setText("");
                txtComplementoClients.setText("");
                txtEstadoClients.setText("");
                txtCidadeClients.setText("");
                txtCepClients.setText("");
                txtTelFixoClients.setText("");
                txtCelularClients.setText("");
                txtEmailClients.setText("");
                txtComplementoClients.setText("");
                txtIdClients.setText("");
                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FClients.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            readJTableForDesc(txtBuscaClients.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FClients.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtBuscaClientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaClientsActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaClientsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clients.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FClients().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTClients;
    private javax.swing.JTextField txtBuscaClients;
    private javax.swing.JTextField txtCelularClients;
    private javax.swing.JTextField txtCepClients;
    private javax.swing.JTextField txtCidadeClients;
    private javax.swing.JTextField txtComplementoClients;
    private javax.swing.JTextField txtCpfClients;
    private javax.swing.JTextField txtEmailClients;
    private javax.swing.JTextField txtEnderecoClients;
    private javax.swing.JTextField txtEstadoClients;
    private javax.swing.JTextField txtIdClients;
    private javax.swing.JTextField txtNomeClients;
    private javax.swing.JTextField txtNumEnderecoClients;
    private javax.swing.JTextField txtTelFixoClients;
    // End of variables declaration//GEN-END:variables
}
