/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.bean.Employees;
import model.dao.EmployeesDAO;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Tong
 */
public class FEmployees extends javax.swing.JFrame {

    /**
     * Creates new form Employees
     */
    public FEmployees() {
        initComponents();
        
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCepEmployees = new javax.swing.JTextField();
        txtEstadoEmployees = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtCidadeEmployees = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtNumEnderecoEmployees = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEnderecoEmployees = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNomeEmployees = new javax.swing.JTextField();
        txtCelularEmployees = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtCpfEmployees = new javax.swing.JTextField();
        txtTelefoFixoEmployees = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtComplementoEmployees = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTEmployees = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtEmailEmployees = new javax.swing.JTextField();
        txtTrabalhoEmployees = new javax.swing.JTextField();
        txtStatusEmployees = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtBuscaEmployees = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtIdEmployees = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtLoginEmployees = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtSenhaEmployees = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtReportaEmployees = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtIdPrivEmployees = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("CIDADE");

        jLabel1.setText("ENDEREÇO");

        jLabel5.setText("NOME");

        jLabel8.setText("CELULAR");

        jLabel2.setText("CPF");

        jLabel6.setText("COMPLEMENTO");

        jLabel3.setText("CEP");

        jLabel7.setText("ESTADO");

        jLabel11.setText("TELEFONE FIXO");

        jLabel9.setText("NUMERO DE ENDEREÇO");

        jTEmployees.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "EMAIL", "CPF", "CELULAR", "TELEFONE FIXO", "CEP", "ENDEREÇO", "Nº ENDEREÇO", "COMPLEMENTO", "CIDADE", "ESTADO", "STATUS", "LOGIN", "SENHA", "TRABALHO", "REPORTA PARA (ID)", "ID PRIVILEGIO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTEmployees.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTEmployeesMouseClicked(evt);
            }
        });
        jTEmployees.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTEmployeesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTEmployees);

        jLabel10.setText("EMAIL");

        jLabel12.setText("STATUS");

        jLabel13.setText("TRABALHO");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtBuscaEmployees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaEmployeesActionPerformed(evt);
            }
        });

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel14.setText("ID");

        jLabel15.setText("LOGIN");

        jLabel16.setText("SENHA");

        jLabel17.setText("REPORTA PARA (ID)");

        jLabel18.setText("ID PRIVILEGIO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(txtNomeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCpfEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtIdEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtCepEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEstadoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtEmailEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(154, 154, 154))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(txtTelefoFixoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(txtCelularEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(txtNumEnderecoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(txtEnderecoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtCidadeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(txtComplementoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(txtStatusEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(txtLoginEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTrabalhoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel17)
                                    .addComponent(txtReportaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(txtSenhaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(txtIdPrivEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(91, 91, 91))))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(30, 30, 30)
                .addComponent(jButton2)
                .addGap(26, 26, 26)
                .addComponent(jButton3)
                .addGap(191, 191, 191)
                .addComponent(txtBuscaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton4))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1181, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtNomeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCpfEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCepEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEstadoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEmailEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtEnderecoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCidadeEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtComplementoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtStatusEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtLoginEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefoFixoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCelularEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumEnderecoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTrabalhoEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSenhaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtBuscaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jButton4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(jButton3)
                                .addComponent(jButton2))))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtIdPrivEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtReportaEmployees, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTEmployees.getModel();
        modelo.setNumRows(0);
        EmployeesDAO pdao = new EmployeesDAO();

        for (Employees p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getEmail(),
                p.getCpf(),
                p.getCell_phone(),
                p.getFixed_phone(),
                p.getCep(),
                p.getAddress(),
                p.getAddress_number(),
                p.getComplement(),
                p.getCity(),
                p.getState(),
                p.getStatus(),
                p.getLogin(),
                p.getPassword(),
                p.getJob_title(),
                p.getReport_to(),
                p.getPrivilegesId()
                
            });

        }

    }
    
    
    public void readJTableForDesc(String desc) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTEmployees.getModel();
        modelo.setNumRows(0);
        EmployeesDAO pdao = new EmployeesDAO();

        for (Employees p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getName(),
                p.getEmail(),
                p.getCpf(),
                p.getCell_phone(),
                p.getFixed_phone(),
                p.getCep(),
                p.getAddress(),
                p.getAddress_number(),
                p.getComplement(),
                p.getCity(),
                p.getState(),
                p.getStatus(),
                p.getLogin(),
                p.getPassword(),
                p.getJob_title(),
                p.getReport_to(),
                p.getPrivilegesId()
            });

        }

    }
    private void jTEmployeesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTEmployeesMouseClicked
        if (jTEmployees.getSelectedRow() != -1) {
            
            txtIdEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 1).toString());
            txtNomeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 2).toString());
            txtEmailEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 3).toString());
            txtCpfEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 4).toString());
            txtCelularEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 5).toString());
            txtTelefoFixoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 6).toString());
            txtCepEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 7).toString()); 
            txtEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 8).toString());
            txtNumEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 9).toString());
            txtComplementoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 10).toString());
            txtCidadeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 11).toString());
            txtEstadoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 12).toString());
            txtStatusEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 13).toString());
            txtLoginEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 14).toString());
            txtSenhaEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 15).toString());
            txtTrabalhoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 16).toString());
            txtReportaEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 17).toString());
            txtIdPrivEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 18).toString());

        }
    }//GEN-LAST:event_jTEmployeesMouseClicked

    private void jTEmployeesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTEmployeesKeyReleased
        if (jTEmployees.getSelectedRow() != -1) {

            txtIdEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 1).toString());
            txtNomeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 2).toString());
            txtEmailEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 3).toString());
            txtCpfEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 4).toString());
            txtCelularEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 5).toString());
            txtTelefoFixoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 6).toString());
            txtCepEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 7).toString()); 
            txtEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 8).toString());
            txtNumEnderecoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 9).toString());
            txtComplementoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 10).toString());
            txtCidadeEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 11).toString());
            txtEstadoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 12).toString());
            txtStatusEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 13).toString());
            txtLoginEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 14).toString());
            txtSenhaEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 15).toString());
            txtTrabalhoEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 16).toString());
            txtReportaEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 17).toString());
            txtIdPrivEmployees.setText(jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 18).toString());

        }
    }//GEN-LAST:event_jTEmployeesKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Employees p = new Employees();
            EmployeesDAO dao = new EmployeesDAO();
            
            p.setId(Integer.parseInt(txtIdEmployees.getText()));
            p.setName(txtNomeEmployees.getText());
            p.setCpf(txtCpfEmployees.getText());
            p.setAddress_number(Integer.parseInt(txtNumEnderecoEmployees.getText()));
            p.setAddress(txtEnderecoEmployees.getText());
            p.setComplement(txtComplementoEmployees.getText());
            p.setState(txtEstadoEmployees.getText());
            p.setCity(txtCidadeEmployees.getText());
            p.setCep(txtCepEmployees.getText());
            p.setFixed_phone(txtTelefoFixoEmployees.getText());
            p.setCell_phone(txtCelularEmployees.getText());
            p.setEmail(txtEmailEmployees.getText());
            p.setStatus(txtStatusEmployees.getText());
            p.setLogin(txtLoginEmployees.getText());
            p.setPassword(txtSenhaEmployees.getText());
            p.setEmployeesId(Integer.parseInt(txtReportaEmployees.getText()));
            p.setPrivilegesId(Integer.parseInt(txtIdPrivEmployees.getText()));
            dao.create(p);
            
            txtIdEmployees.setText("");
            txtNomeEmployees.setText("");
            txtEmailEmployees.setText("");
            txtCpfEmployees.setText("");
            txtCelularEmployees.setText("");
            txtTelefoFixoEmployees.setText("");
            txtCepEmployees.setText(""); 
            txtEnderecoEmployees.setText("");
            txtNumEnderecoEmployees.setText("");
            txtComplementoEmployees.setText("");
            txtCidadeEmployees.setText("");
            txtEstadoEmployees.setText("");
            txtStatusEmployees.setText("");
            txtLoginEmployees.setText("");
            txtSenhaEmployees.setText("");
            txtTrabalhoEmployees.setText("");
            txtReportaEmployees.setText("");
            txtIdPrivEmployees.setText("");


            
            readJTable();

        } catch (SQLException ex) {
            Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTEmployees.getSelectedRow() != -1) {

            try {

                Employees p = new Employees();
                EmployeesDAO dao = new EmployeesDAO();

                p.setId((int) jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 0));

                dao.delete(p);

                txtIdEmployees.setText("");
                txtNomeEmployees.setText("");
                txtEmailEmployees.setText("");
                txtCpfEmployees.setText("");
                txtCelularEmployees.setText("");
                txtTelefoFixoEmployees.setText("");
                txtCepEmployees.setText(""); 
                txtEnderecoEmployees.setText("");
                txtNumEnderecoEmployees.setText("");
                txtComplementoEmployees.setText("");
                txtCidadeEmployees.setText("");
                txtEstadoEmployees.setText("");
                txtStatusEmployees.setText("");
                txtLoginEmployees.setText("");
                txtSenhaEmployees.setText("");
                txtTrabalhoEmployees.setText("");
                txtReportaEmployees.setText("");
                txtIdPrivEmployees.setText("");

                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione um empregado para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTEmployees.getSelectedRow() != -1) {

            try {

                Employees p = new Employees();
                EmployeesDAO dao = new EmployeesDAO();

               p.setId(Integer.parseInt(txtIdEmployees.getText()));
                p.setName(txtNomeEmployees.getText());
                p.setCpf(txtCpfEmployees.getText());
                p.setAddress_number(Integer.parseInt(txtNumEnderecoEmployees.getText()));
                p.setAddress(txtEnderecoEmployees.getText());
                p.setComplement(txtComplementoEmployees.getText());
                p.setState(txtEstadoEmployees.getText());
                p.setCity(txtCidadeEmployees.getText());
                p.setCep(txtCepEmployees.getText());
                p.setFixed_phone(txtTelefoFixoEmployees.getText());
                p.setCell_phone(txtCelularEmployees.getText());
                p.setEmail(txtEmailEmployees.getText());
                p.setStatus(txtStatusEmployees.getText());
                p.setLogin(txtLoginEmployees.getText());
                p.setPassword(txtSenhaEmployees.getText());
                p.setEmployeesId(Integer.parseInt(txtReportaEmployees.getText()));
                p.setPrivilegesId(Integer.parseInt(txtIdPrivEmployees.getText()));
                p.setId((int) jTEmployees.getValueAt(jTEmployees.getSelectedRow(), 0));

                try {
                    dao.alter(p);
                } catch (SQLException ex) {
                    Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
                }

                txtIdEmployees.setText("");
                txtNomeEmployees.setText("");
                txtEmailEmployees.setText("");
                txtCpfEmployees.setText("");
                txtCelularEmployees.setText("");
                txtTelefoFixoEmployees.setText("");
                txtCepEmployees.setText(""); 
                txtEnderecoEmployees.setText("");
                txtNumEnderecoEmployees.setText("");
                txtComplementoEmployees.setText("");
                txtCidadeEmployees.setText("");
                txtEstadoEmployees.setText("");
                txtStatusEmployees.setText("");
                txtLoginEmployees.setText("");
                txtSenhaEmployees.setText("");
                txtTrabalhoEmployees.setText("");
                txtReportaEmployees.setText("");
                txtIdPrivEmployees.setText("");
                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtBuscaEmployeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaEmployeesActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaEmployeesActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            readJTableForDesc(txtBuscaEmployees.getText());
        } catch (SQLException ex) {
            Logger.getLogger(FEmployees.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FEmployees.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FEmployees().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTEmployees;
    private javax.swing.JTextField txtBuscaEmployees;
    private javax.swing.JTextField txtCelularEmployees;
    private javax.swing.JTextField txtCepEmployees;
    private javax.swing.JTextField txtCidadeEmployees;
    private javax.swing.JTextField txtComplementoEmployees;
    private javax.swing.JTextField txtCpfEmployees;
    private javax.swing.JTextField txtEmailEmployees;
    private javax.swing.JTextField txtEnderecoEmployees;
    private javax.swing.JTextField txtEstadoEmployees;
    private javax.swing.JTextField txtIdEmployees;
    private javax.swing.JTextField txtIdPrivEmployees;
    private javax.swing.JTextField txtLoginEmployees;
    private javax.swing.JTextField txtNomeEmployees;
    private javax.swing.JTextField txtNumEnderecoEmployees;
    private javax.swing.JTextField txtReportaEmployees;
    private javax.swing.JTextField txtSenhaEmployees;
    private javax.swing.JTextField txtStatusEmployees;
    private javax.swing.JTextField txtTelefoFixoEmployees;
    private javax.swing.JTextField txtTrabalhoEmployees;
    // End of variables declaration//GEN-END:variables
}
