/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import model.dao.OrdersDAO;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.bean.Orders;
/**
 *
 * @author Tong
 */
public class Forders extends javax.swing.JFrame {

    /**
     * Creates new form Orders
     */
    public Forders() {
        initComponents();
        
        jButton4.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIdOrders = new javax.swing.JTextField();
        txtDescontoOrders = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDataOrders = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtSituacaoOrders = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtObservacoesOrders = new javax.swing.JTextField();
        txtPrecoTotalOrders = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTOrders = new javax.swing.JTable();
        txtBuscaOrders = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        txtIdEmpregadoOrders = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtIdBudgetOrders = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel4.setText("DATA");

        jLabel1.setText("SITUAÇÃO");

        jLabel5.setText("PREÇO TOTAL");

        jLabel9.setText("ID");

        jLabel11.setText("OBSERVAÇÕES");

        jLabel2.setText("DESCONTO");

        jTOrders.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "DESCONTO", "OBSERVAÇÕES", "PREÇO TOTAL", "SITUAÇÃO", "DATA", "ID EMPREGADO", "ID BUDGET"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTOrders.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTOrdersMouseClicked(evt);
            }
        });
        jTOrders.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTOrdersKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(jTOrders);

        txtBuscaOrders.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscaOrdersActionPerformed(evt);
            }
        });

        jButton4.setText("Busca");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Excluir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Atualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel10.setText("ID EMPREGADO");

        jLabel12.setText("ID BUDGET");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addGap(30, 30, 30)
                                .addComponent(jButton2)
                                .addGap(26, 26, 26)
                                .addComponent(jButton3)
                                .addGap(56, 56, 56)
                                .addComponent(txtBuscaOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(txtPrecoTotalOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtDescontoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(txtSituacaoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(26, 26, 26)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(txtDataOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(txtObservacoesOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtIdOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel9))
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(txtIdEmpregadoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(txtIdBudgetOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(170, 170, 170)
                                .addComponent(jLabel2)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5)
                                .addComponent(jLabel9))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtIdOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdEmpregadoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtPrecoTotalOrders, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDescontoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtIdBudgetOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSituacaoOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtObservacoesOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton3)
                        .addComponent(jButton2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtBuscaOrders, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void readJTable() throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTOrders.getModel();
        modelo.setNumRows(0);
        OrdersDAO pdao = new OrdersDAO();

        for (Orders p : pdao.read()) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDiscount(),
                p.getObservation(),
                p.getPayment(),
                p.getSituation(),
                p.getDate(),
                p.getEmployeesId(),
                p.getBudgetsId()
            });

        }

    }
    
    
    public void readJTableForDesc(String desc) throws SQLException {
        
        DefaultTableModel modelo = (DefaultTableModel) jTOrders.getModel();
        modelo.setNumRows(0);
        OrdersDAO pdao = new OrdersDAO();

        for (Orders p : pdao.readForDesc(desc)) {

            modelo.addRow(new Object[]{
                p.getId(),
                p.getDiscount(),
                p.getObservation(),
                p.getPayment(),
                p.getSituation(),
                p.getDate(),
                p.getEmployeesId(),
                p.getBudgetsId()
            });

        }
    }
    
    private void jTOrdersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTOrdersMouseClicked
        if (jTOrders.getSelectedRow() != -1) {

            txtIdOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 1).toString());
            txtDescontoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 2).toString());
            txtObservacoesOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 3).toString());
            txtPrecoTotalOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 4).toString());
            txtSituacaoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 5).toString());
            txtDataOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 6).toString());
            txtIdEmpregadoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 7).toString());
            txtIdBudgetOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 8).toString());
            
        }
    }//GEN-LAST:event_jTOrdersMouseClicked

    private void jTOrdersKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTOrdersKeyReleased
        if (jTOrders.getSelectedRow() != -1) {

            txtIdOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 1).toString());
            txtDescontoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 2).toString());
            txtObservacoesOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 3).toString());
            txtPrecoTotalOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 4).toString());
            txtSituacaoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 5).toString());
            txtDataOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 6).toString());
            txtIdEmpregadoOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 7).toString());
            txtIdBudgetOrders.setText(jTOrders.getValueAt(jTOrders.getSelectedRow(), 8).toString());
        }
    }//GEN-LAST:event_jTOrdersKeyReleased

    private void txtBuscaOrdersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaOrdersActionPerformed
        jButton4.setEnabled(true);
    }//GEN-LAST:event_txtBuscaOrdersActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        try {
            readJTableForDesc(txtBuscaOrders.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Forders.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Orders p = new Orders();
            OrdersDAO dao = new OrdersDAO();

            p.setId(Integer.parseInt(txtIdOrders.getText()));
            p.setDiscount(Double.parseDouble(txtDescontoOrders.getText()));
            p.setObservation(txtObservacoesOrders.getText());
            p.setPayment(txtPrecoTotalOrders.getText());
            p.setSituation(txtDataOrders.getText());
            p.setEmployeesId(Integer.parseInt(txtIdEmpregadoOrders.getText()));
            p.setBudgetsId(Integer.parseInt(txtIdBudgetOrders.getText()));
            dao.create(p);

            
            txtIdOrders.setText("");
            txtDescontoOrders.setText("");
            txtObservacoesOrders.setText("");
            txtPrecoTotalOrders.setText("");
            txtSituacaoOrders.setText("");
            txtDataOrders.setText("");
            txtIdEmpregadoOrders.setText("");
            txtIdBudgetOrders.setText("");
            

            readJTable();

        } catch (SQLException ex) {
            Logger.getLogger(Forders.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (jTOrders.getSelectedRow() != -1) {

            try {

                Orders p = new Orders();
                OrdersDAO dao = new OrdersDAO();

                p.setId((int) jTOrders.getValueAt(jTOrders.getSelectedRow(), 0));

                dao.delete(p);

                txtIdOrders.setText("");
                txtDescontoOrders.setText("");
                txtObservacoesOrders.setText("");
                txtPrecoTotalOrders.setText("");
                txtSituacaoOrders.setText("");
                txtDataOrders.setText("");
                txtIdEmpregadoOrders.setText("");
                txtIdBudgetOrders.setText("");

                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(Forders.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma ordem para excluir.");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (jTOrders.getSelectedRow() != -1) {

            try {

                Orders p = new Orders();
                OrdersDAO dao = new OrdersDAO();
                
                p.setId(Integer.parseInt(txtIdOrders.getText()));
                p.setDiscount(Double.parseDouble(txtDescontoOrders.getText()));
                p.setObservation(txtObservacoesOrders.getText());
                p.setPayment(txtPrecoTotalOrders.getText());
                p.setSituation(txtDataOrders.getText());
                p.setEmployeesId(Integer.parseInt(txtIdEmpregadoOrders.getText()));
                p.setBudgetsId(Integer.parseInt(txtIdBudgetOrders.getText()));
                p.setId((int) jTOrders.getValueAt(jTOrders.getSelectedRow(), 0));

                try {
                    dao.alter(p);
                } catch (SQLException ex) {
                    Logger.getLogger(Forders.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Forders.class.getName()).log(Level.SEVERE, null, ex);
                }

                txtIdOrders.setText("");
                txtDescontoOrders.setText("");
                txtObservacoesOrders.setText("");
                txtPrecoTotalOrders.setText("");
                txtSituacaoOrders.setText("");
                txtDataOrders.setText("");
                txtIdEmpregadoOrders.setText("");
                txtIdBudgetOrders.setText("");
                readJTable();

            } catch (SQLException ex) {
                Logger.getLogger(Forders.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forders.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Forders().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTOrders;
    private javax.swing.JTextField txtBuscaOrders;
    private javax.swing.JTextField txtDataOrders;
    private javax.swing.JTextField txtDescontoOrders;
    private javax.swing.JTextField txtIdBudgetOrders;
    private javax.swing.JTextField txtIdEmpregadoOrders;
    private javax.swing.JTextField txtIdOrders;
    private javax.swing.JTextField txtObservacoesOrders;
    private javax.swing.JTextField txtPrecoTotalOrders;
    private javax.swing.JTextField txtSituacaoOrders;
    // End of variables declaration//GEN-END:variables
}
